"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 750

[character]
success_symbol = "(bold_green)"
error_symbol = "(bold_red)"

[directory]
style = "sky"

[git_branch]
symbol = "ğŸŒ±"
format = "[$symbol$branch(:$remote_branch) ]($style) "
style = "bold bg:mauve fg:mantle"
ignore_branches = ["main", "master"]

[git_status]
format = '([$all_status$ahead_behind]($style) )'
stashed = "ğŸ“¦"
modified = "ğŸ“"
conflicted = "ğŸ’¥"
untracked = "ğŸ¤·"
deleted = "âŒ"
renamed = "ğŸ“›"
staged = "ğŸšš"
ahead = "ğŸš€"
behind = "ğŸ‘‡"
